apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: http-events
spec:
  type: pubsub.kafka
  version: v1
  metadata:
      # Kafka broker connection setting
    - name: brokers
      value: "http-events-kafka-0.http-events-kafka-brokers.default.svc:9092,http-events-kafka-1.http-events-kafka-brokers.default.svc:9092,http-events-kafka-2.http-events-kafka-brokers.default.svc:9092"
    - name: authRequired
      value: "false"
    - name: maxMessageBytes
      value: 1024
#scopes:
#- nginx-ingress
#- http-event-subscriber